name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  test:

    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', 'jruby-9.2.9.0']

    services:
      cassandra:
        image: cassandra:2.1.18
        ports:
          - 9042:9042
        options: --name cassandra_test --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
